### ISSUE TITLE
Cannot access server outside container

### ISSUE THREAD

**Issue by freakynit** [TileDB-Inc/TileDB-MariaDB#299]
It seems the Mariadb instance started inside container binds to just localhost. Any way around this? I would like to start mariadb with tiledb storage inside container, but, access it from host OS.

**Comment by Shelnutt2** [comment]
Hello @freakynit you can allow access outside the container by using docker to map the ports.

Something like:
```
docker run -d -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -p3306:3306 tiledb/tiledb-mariadb-server
```
After this start you can access the MariaDB instance from your host with:
```
mysql -h127.0.0.1 -P3306 -uroot
```

Although you likely don't want to do `MYSQL_ALLOW_EMPTY_PASSWORD` unless this is just for testing.


If you are wanting to mount a folder or directory for where data will be stored you can use [docker's volume option `-v`](https://docs.docker.com/engine/reference/commandline/run/#volume). You should also be able to access S3 or other network storage locations from docker if you have appropriate credentials setup, happy to provide examples if you'd like!

**Comment by freakynit** [comment]
Thanks a lot @Shelnutt2 . This worked. Weird thing though I have been trying this exact port exposing thing for the past 3 days, but it wasn't working... but, worked today.

Thanks again.. we can close this issue.

**Comment by Shelnutt2** [comment]
> Thanks a lot @Shelnutt2 . This worked. Weird thing though I have been trying this exact port exposing thing for the past 3 days, but it wasn't working... but, worked today.
> 
> Thanks again.. we can close this issue.

@freakynit glad this worked for you. We have a few different docker images, perhaps you were not using the `tiledb/tiledb-mariadb-server`? Some of our other images don't expose the port, which could explain it.

**Comment by freakynit** [comment]
Yup... I believe I was trying with the image that gives shell access (`tiledb/tiledb-mariadb`).
